TIPO_PROCEDIMENTO_CONSULTA = "consulta"
TIPO_PROCEDIMENTO_AMBULATORIAL = "procedimento-ambulatorial"
TIPO_PROCEDIMENTO_CIRURGIA = "cirurgia"
TIPO_PROCEDIMENTO_METODOS_ELETROFISIOLOGICOS = "metodos-eletrofisiologicos"
TIPO_PROCEDIMENTO_ENDOSCOPIA = "endoscopia"
TIPO_PROCEDIMENTO_MEDICINA_LABORATORIAL = "medicina-laboratorial"
TIPO_PROCEDIMENTO_MEDICINA_TRANSFUSIONAL = "medicina-transfusional"
TIPO_PROCEDIMENTO_GENETICA = "genetica"
TIPO_PROCEDIMENTO_ANATOMIA_PATOLOGICA = "anatomia-patologica-citopatologia"
TIPO_PROCEDIMENTO_MEDICINA_NUCLEAR = "medicina-nuclear"
TIPO_PROCEDIMENTO_RADIOLOGIA_RX = "radiologia-rx"
TIPO_PROCEDIMENTO_ULTRASSONOGRAFIA_US = "ultrassonografia-us"
TIPO_PROCEDIMENTO_TOMOGRAFIA_COMPUTADORIZADA = "tomografia-computadorizada"
TIPO_PROCEDIMENTO_RESSONANCIA_MAGNETICA = "ressonancia-magnetica"
TIPO_PROCEDIMENTO_RADIOTERAPIA = "radioterapia"
TIPO_PROCEDIMENTO_EXAMES_ESPECIFICOS = "exames-procedimentos-especificos"
TIPO_PROCEDIMENTO_TESTES_DIAGNOSTICO = "testes-diagnostico"
TIPO_PROCEDIMENTO_OUTROS_DIAGNOSTICOS_TERAPEUTICOS = "outros-diagnosticos-terapeuticos"
TIPO_PROCEDIMENTO_OUTROS = "outros"
TIPO_PROCEDIMENTO_NAO_INFORMADO = "nao-informado"

CODIGOS_TUSS_CONSULTA_EXATOS = {"5001"}
FAIXAS_TUSS_CONSULTA = ((10000000, 19999999),)

TIPO_PROCEDIMENTO_LABELS = {
    TIPO_PROCEDIMENTO_CONSULTA: "Consultas",
    TIPO_PROCEDIMENTO_AMBULATORIAL: "Procedimentos ambulatoriais",
    TIPO_PROCEDIMENTO_CIRURGIA: "Cirurgias",
    TIPO_PROCEDIMENTO_METODOS_ELETROFISIOLOGICOS: "Métodos Eletrofisiológicos/Mecânicos e Funcionais",
    TIPO_PROCEDIMENTO_ENDOSCOPIA: "Endoscopia",
    TIPO_PROCEDIMENTO_MEDICINA_LABORATORIAL: "Medicina Laboratorial",
    TIPO_PROCEDIMENTO_MEDICINA_TRANSFUSIONAL: "Medicina Transfusional",
    TIPO_PROCEDIMENTO_GENETICA: "Genética",
    TIPO_PROCEDIMENTO_ANATOMIA_PATOLOGICA: "Anatomia Patológica e Citopatologia",
    TIPO_PROCEDIMENTO_MEDICINA_NUCLEAR: "Medicina Nuclear",
    TIPO_PROCEDIMENTO_RADIOLOGIA_RX: "Radiologia / RX",
    TIPO_PROCEDIMENTO_ULTRASSONOGRAFIA_US: "Ultrassonografia (US)",
    TIPO_PROCEDIMENTO_TOMOGRAFIA_COMPUTADORIZADA: "Tomografia Computadorizada (TC)",
    TIPO_PROCEDIMENTO_RESSONANCIA_MAGNETICA: "Ressonância Magnética (RM)",
    TIPO_PROCEDIMENTO_RADIOTERAPIA: "Radioterapia",
    TIPO_PROCEDIMENTO_EXAMES_ESPECIFICOS: "Exames/Procedimentos Específicos",
    TIPO_PROCEDIMENTO_TESTES_DIAGNOSTICO: "Testes para Diagnóstico",
    TIPO_PROCEDIMENTO_OUTROS_DIAGNOSTICOS_TERAPEUTICOS: "Outros Procedimentos Diagnósticos/Terapêuticos",
    TIPO_PROCEDIMENTO_OUTROS: "Outros",
    TIPO_PROCEDIMENTO_NAO_INFORMADO: "Não informado",
}

TIPOS_PROCEDIMENTO_VALIDOS = set(TIPO_PROCEDIMENTO_LABELS.keys())

FAIXAS_TUSS = (
    (*FAIXAS_TUSS_CONSULTA[0], TIPO_PROCEDIMENTO_CONSULTA),
    (20000000, 29999999, TIPO_PROCEDIMENTO_AMBULATORIAL),
    (30000000, 39999999, TIPO_PROCEDIMENTO_CIRURGIA),
    (40100000, 40199999, TIPO_PROCEDIMENTO_METODOS_ELETROFISIOLOGICOS),
    (40200000, 40299999, TIPO_PROCEDIMENTO_ENDOSCOPIA),
    (40300000, 40399999, TIPO_PROCEDIMENTO_MEDICINA_LABORATORIAL),
    (40400000, 40499999, TIPO_PROCEDIMENTO_MEDICINA_TRANSFUSIONAL),
    (40500000, 40599999, TIPO_PROCEDIMENTO_GENETICA),
    (40600000, 40699999, TIPO_PROCEDIMENTO_ANATOMIA_PATOLOGICA),
    (40700000, 40799999, TIPO_PROCEDIMENTO_MEDICINA_NUCLEAR),
    (40800000, 40899999, TIPO_PROCEDIMENTO_RADIOLOGIA_RX),
    (40900000, 40999999, TIPO_PROCEDIMENTO_ULTRASSONOGRAFIA_US),
    (41000000, 41099999, TIPO_PROCEDIMENTO_TOMOGRAFIA_COMPUTADORIZADA),
    (41100000, 41199999, TIPO_PROCEDIMENTO_RESSONANCIA_MAGNETICA),
    (41200000, 41299999, TIPO_PROCEDIMENTO_RADIOTERAPIA),
    (41300000, 41399999, TIPO_PROCEDIMENTO_EXAMES_ESPECIFICOS),
    (41400000, 41499999, TIPO_PROCEDIMENTO_TESTES_DIAGNOSTICO),
    (41500000, 41599999, TIPO_PROCEDIMENTO_OUTROS_DIAGNOSTICOS_TERAPEUTICOS),
)


def normalizar_codigo_tuss(valor):
    if valor is None:
        return ""

    texto = str(valor).strip()
    if not texto:
        return ""

    try:
        codigo = int(valor)
    except (TypeError, ValueError):
        try:
            codigo = int(float(texto.replace(",", ".")))
        except (TypeError, ValueError):
            return ""

    if codigo <= 0:
        return ""

    return str(codigo)


def tipo_procedimento_codigo(codigo):
    codigo_texto = normalizar_codigo_tuss(codigo)
    if not codigo_texto:
        return TIPO_PROCEDIMENTO_NAO_INFORMADO

    codigo_int = int(codigo_texto)
    if codigo_texto in CODIGOS_TUSS_CONSULTA_EXATOS:
        return TIPO_PROCEDIMENTO_CONSULTA

    for inicio, fim, tipo in FAIXAS_TUSS:
        if inicio <= codigo_int <= fim:
            return tipo

    return TIPO_PROCEDIMENTO_OUTROS


def label_tipo_procedimento(tipo):
    return TIPO_PROCEDIMENTO_LABELS.get(tipo, TIPO_PROCEDIMENTO_LABELS[TIPO_PROCEDIMENTO_NAO_INFORMADO])
