ROLE_MEDICO = "medico"
ROLE_RECEPCAO = "recepcao"
ROLE_COORD_RECEPCAO = "coord_recepcao"
ROLE_DPO = "dpo"
ROLE_TI = "ti"
ROLE_ADMIN = "admin"
ROLE_COORD_FINANCEIRO = "coord_financeiro"

ROLES_USUARIO = {
    ROLE_MEDICO,
    ROLE_RECEPCAO,
    ROLE_COORD_RECEPCAO,
    ROLE_DPO,
    ROLE_TI,
    ROLE_ADMIN,
    ROLE_COORD_FINANCEIRO,
}

MEDICO_ROLES = (ROLE_MEDICO,)
RECEPCAO_ROLES = (ROLE_RECEPCAO, ROLE_COORD_RECEPCAO, ROLE_ADMIN)
COORD_RECEPCAO_ROLES = (ROLE_COORD_RECEPCAO, ROLE_ADMIN)
LGPD_ROLES = (ROLE_ADMIN, ROLE_DPO, ROLE_TI)
ADMIN_ROLES = (ROLE_ADMIN,)
FINANCEIRO_ROLES = (ROLE_COORD_FINANCEIRO, ROLE_ADMIN)

ROLES_EXIGEM_UNIDADE = {ROLE_MEDICO, ROLE_RECEPCAO, ROLE_COORD_RECEPCAO}


__all__ = [
    "ADMIN_ROLES",
    "COORD_RECEPCAO_ROLES",
    "FINANCEIRO_ROLES",
    "LGPD_ROLES",
    "MEDICO_ROLES",
    "RECEPCAO_ROLES",
    "ROLE_ADMIN",
    "ROLE_COORD_FINANCEIRO",
    "ROLE_COORD_RECEPCAO",
    "ROLE_DPO",
    "ROLE_MEDICO",
    "ROLE_RECEPCAO",
    "ROLE_TI",
    "ROLES_EXIGEM_UNIDADE",
    "ROLES_USUARIO",
]
